# Generated by Django 5.2.17 on 2026-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_REALIZACAO', 'Em realização'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
            ],
            options={
                'db_table': 'manutencoes',
                'ordering': ['data_inicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('LEVE', 'Leve'), ('PESADO', 'Pesado')], max_length=20)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veiculos',
                'ordering': ['placa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('km_percorrida', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'viagens',
                'ordering': ['-data_saida'],
                'managed': False,
            },
        ),
    ]
